### ISSUE TITLE
[버그] 

### ISSUE THREAD

**Issue by cuel01** [Team-int/intbot#18]
**버그 설명하기**
갬블 확률?...

**버그 발생시키기**
!도박 숫자

**예상된 결과**
2여야할게 5여서 확률에 살짝 문제가 있던 버그

**스크린샷**
gambling.js 46번 줄
![캡처](https://user-images.githubusercontent.com/83503535/120106043-6fcea180-c196-11eb-9dde-049c1bf95da2.PNG)

**기타 내용**
의도하고 일부러 그렇게 하거나 너무 자잘한거면 죄송하네요

**Comment by MadeGOD** [comment]
해당 내용을 확인하였으나 아래 내용으로 버그가 아니라는것이 증면되었습니다.
* 버그가 아님
* 확율 밸런스를 위해 만들어진 기능
임으로 재현 불가능합니다
