### ISSUE TITLE
[버그] 주식 남은 시간 계산 

### ISSUE THREAD

**Issue by cuel01** [Team-int/intbot#22]
**버그 설명하기**
주식 남은 시간 계산이 잘 못 된다

**버그 발생시키기**
인트야 주식을 10초 전, 10초 후에 친다

**예상된 결과**
10초->0초, 0초->60초, 60->50초

**스크린샷**
![image](https://user-images.githubusercontent.com/83503535/120189785-b7b2fe80-c252-11eb-9a5d-63f3e8cb8f2b.png)
위와 같이 10초->50초, 50->60초, 60->50으로 가는 이상한 시간이 나타납니다

**기타 내용**
버그 수정을 하기는 했는데 자신이 없습니다;;

**Comment by MadeGOD** [comment]
@sujang956

**Comment by MadeGOD** [comment]
@sujang958

**Comment by MadeGOD** [comment]
해당 버그는 호스팅 시작 도중에 꼬임 문제임으로 알아서 해결이 됩니다.
