### ISSUE TITLE
[버그] 말도 안되는 시간이 뜨는 버그

### ISSUE THREAD

**Issue by cuel01** [Team-int/intbot#24]
**버그 설명하기**
말도 안되는 시간이 뜸

**버그 발생시키기**
인트야 주식을 친다

**예상된 결과**
0~23시인 정상적인 시간이 떠야한다

**스크린샷**
![image](https://user-images.githubusercontent.com/83503535/121039561-26accc00-c7ec-11eb-9d42-a74974583727.png)

**기타 내용**
또 말씀해주실 내용이 있다면 작성해주세요.

**Comment by MadeGOD** [comment]
스타일 오류가 났습니다. `npm lint:fix` 로 해결해 주시기 바랍니다.

**Comment by MadeGOD** [comment]
호스팅 이전으로 국가가 변경되어서 발생된겁니다. 해결되었습니다.
