### ISSUE TITLE
[버그] 

### ISSUE THREAD

**Issue by sujang958** [team-int/intbot#3]
**버그 설명하기**
빼애액

**버그 발생시키기**
버그를 발생시키는 방법입니다.

**예상된 결과**
일반적으로 발생해야하는 결과입니다.

**스크린샷**
스크린샷이 있다면 첨부해주세요.

**기타 내용**
또 말씀해주실 내용이 있다면 작성해주세요.

**Comment by chul0721** [comment]
네

**Comment by chul0721** [comment]
처리하겠습니다.
